sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.5-dev'
- 'nightly'
install:
- pip install -r requirements.txt
- pip install -e .
script: py.test
env:
  # See README for information on variables needed for testing
  # - LTD_MASON_TEST_AWS_ID
  # - LTD_MASON_TEST_AWS_SECRET
  # - LTD_MASON_TEST_BUCKET
  global:
  - LTD_MASON_TEST_AWS_ID=AKIAJQTXPK2NYX2KHS7Q
  # travis encrypt "LTD_MASON_TEST_AWS_SECRET=... LTD_MASON_TEST_BUCKET=..." --add env.global
  - secure: IwwOxrEuGJ2J17WkYltWSq60WSyHOvH4ie0FccpvL7zZ3F8ca2rtLKpwW66Huv4TkkC1eYdw9B2v8hY8YtHsn9FkrnXYpTSd+2cyKO5S/y7D0BRKb5WfdvKa/a0NKDswlTKXvmca+8/Su3BhAAF+A8GOWRjHc04O4O3C+gWquch6+21cCIXcUEHDnDOLvnLDRZ3WQDVvQfKD7ZWOxYw/M8v/tas5qF/yvm+/8TGFkC+NHKGKll2SZDUd03iAYSIhekzqGx2peqGoBtk3TBThEYaW91PEae0N1bqgyPL4qhjkBxUtIFk5tRpFjJR3J3kSWTMx30TQk1VBvOHrN83DkHNZLG56K+ygv6F5yB+mkxYZNugeaSHEtWLVs7p4b38A0rofLwUP77RYHPE+TeKCKXqhF4WGv1w+CHVfYiXEeaI6AeHJz9ta66+9y3+d7uJBFim2haM8K48rj69ycIRmOw6xbtUn7GYMBHgF96lx9OSkq6vL0bh2l6O3NOFoqpgTDcZ6fENJQ+9YnRwaQk2WWx/KoeWMR0Q3QSoYzUTsrgSYgDIvEW3Vdmcfk9l1Er+GuQxJeyXjscZzRF3ix0aWJfqnS9KRD7mawvNjZfFU3pCcE6hcqZCZ1ZMJcomxl71bpMV6MYhLFiKiKvH6LrpwD+xHpz3qanAjjj3JvHUfqnQ=
